# Generated by Django 3.0 on 2023-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SUMMARIZES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='请求时间')),
                ('input_text', models.CharField(max_length=1000, verbose_name='输入内容')),
                ('summary', models.CharField(max_length=1000, verbose_name='总结内容')),
            ],
            options={
                'db_table': 'summarizes',
            },
        ),
    ]
