# Generated by Django 3.0 on 2023-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizes',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='请求时间'),
        ),
    ]
